modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Flytre" #optional
[[mods]] #mandatory
modId="extratnt" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Extra TNT" #mandatory
displayURL="https://flytre.net/" #optional
logoFile="extratnt.png" #optional
credits="By Flytre" #optional
authors="Flytre" #optional
description='''
Adds 5 brand new TNTs, with various explosion sizes and animations to make your world a more fun place!
'''
[[dependencies.extratnt]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.extratnt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
